name: CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

env:
  FORCE_COLOR: 1

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: Lint
        run: pnpm run lint

  typecheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: Typecheck
        run: pnpm run typecheck

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: Run unit tests
        run: pnpm run test:coverage

      - name: Run e2e tests
        run: pnpm run test:playground

  build:
    runs-on: ubuntu-latest

    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: Build
        run: pnpm run build

  linkcheck:
    runs-on: ubuntu-latest

    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: Build
        run: pnpm run build
        env:
          PROSEKIT_NO_CLEAN_URLS: true

      - name: Check links
        uses: lycheeverse/lychee-action@v1.9.0
        with:
          args: --base ./website/dist --verbose --no-progress './website/dist/**/*.html' --include-fragments
          fail: true

  deploy:
    runs-on: ubuntu-latest

    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: Build
        run: pnpm run build:website

      # When deploying to Netlify, sometimes the build fails with 422 Unprocessable
      # Entity error. I suspect it's because I deploy the same content in a short time.
      # As a workaround, a unique file is created for each build.
      - name: Add random file
        run: |
          uuidgen >> ./website/dist/build.log
          date >> ./website/dist/build.log

      - name: Deploy to Netlify
        id: deploy-1
        uses: nwtgck/actions-netlify@v2.1
        continue-on-error: true
        with:
          publish-dir: './website/dist'
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Deploy from GitHub Actions'
          enable-pull-request-comment: true
          enable-commit-comment: false
          enable-commit-status: false
          overwrites-pull-request-comment: true
          alias: ${{ github.head_ref }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_WEBSITE_SITE_ID }}
        timeout-minutes: 5

      - name: Add random file (retry)
        if: steps.deploy-1.outcome == 'failure'
        run: |
          sleep 30
          uuidgen >> ./website/dist/build.log
          date >> ./website/dist/build.log

      - name: Deploy to Netlify (retry)
        id: deploy-2
        if: steps.deploy-1.outcome == 'failure'
        uses: nwtgck/actions-netlify@v2.1
        with:
          publish-dir: './website/dist'
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Deploy from GitHub Actions (retry)'
          enable-pull-request-comment: false
          enable-commit-comment: false
          enable-commit-status: false
          overwrites-pull-request-comment: true
          alias: ${{ github.head_ref }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_WEBSITE_SITE_ID }}
        timeout-minutes: 5
