# https://autofix.ci/setup

name: autofix.ci

on:
  pull_request:

permissions:
  contents: read

jobs:
  fix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: Fix
        run: nr fix

      - uses: autofix-ci/action@bee19d72e71787c12ca0f29de72f2833e437e4c9
