name: Release

on:
  push:
    branches:
      - master

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm ci:version
          commit: 'chore: version packages'
          title: 'chore: version packages'
          createGithubReleases: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: Publish to NPM
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ".npmrc"
          pnpm ci:publish
          rm ".npmrc"

      - name: Get package version
        run: |
          PROSEKIT_VERSION=$(jq -r ".version" packages/prosekit/package.json)
          echo "PROSEKIT_RELEASE_TAG=v${PROSEKIT_VERSION}" >> "$GITHUB_ENV"

      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          commit: master
          tag: '${{ env.PROSEKIT_RELEASE_TAG }}'
          body: 'Please refer to [CHANGELOG.md](https://github.com/ocavue/prosekit/blob/${{ env.PROSEKIT_RELEASE_TAG }}/packages/prosekit/CHANGELOG.md) for details.'
          token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
