name: "size"
on:
  pull_request:
    branches:
      - master
jobs:
  size:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup

      - name: Set environment variables
        run: |
          echo 'NODE_OPTIONS=--max_old_space_size=8192' >> "$GITHUB_ENV"

      - uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build_script: build:package
