name: Snapshot Release

on:
  issue_comment:
    types: [created]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/publish') && github.event.comment.user.login == 'ocavue' }}
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup

      - name: Print PR infomation
        run: |
          echo "PR number:" $PR_NUMBER
          echo "comment body:" $COMMENT_BODY
        env:
          PR_NUMBER: ${{ github.event.issue.number }}
          COMMENT_BODY: ${{ github.event.comment.body }}

      - name: Checkout to PR
        run: |
          gh pr checkout $PR_NUMBER
          pnpm install
        env:
          PR_NUMBER: ${{ github.event.issue.number }}

      - name: Add changeset
        run: cp config/snapshot-changeset.md .changeset/

      - name: Update package version
        run: pnpm ci:version:next

      - name: Publish to NPM
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ".npmrc"
          pnpm ci:publish:next
          rm ".npmrc"
