name: Snapshot Release

on:
  issue_comment:
    types: [created]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/publish') && github.event.comment.user.login == 'ocavue' }}
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: Print PR infomation
        run: |
          echo "PR number:" $PR_NUMBER
          echo "comment body:" $COMMENT_BODY
        env:
          PR_NUMBER: ${{ github.event.issue.number }}
          COMMENT_BODY: ${{ github.event.comment.body }}

      - name: Checkout to PR
        run: |
          gh pr checkout $PR_NUMBER
          pnpm install
        env:
          PR_NUMBER: ${{ github.event.issue.number }}
          GH_TOKEN: ${{ github.token }}

      - name: Add changeset
        run: cp config/snapshot-changeset.md .changeset/

      - name: Update package version
        run: pnpm ci:version:next

      - name: Build packages
        run: pnpm build:package

      - name: Publish to NPM
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ".npmrc"
          pnpm ci:publish:next
          rm ".npmrc"

      - name: Get version number
        run: |
          NPM_VERSION_NUMBER=$(cat packages/prosekit/package.json | jq -r .version)
          echo "NPM_VERSION_NUMBER=$NPM_VERSION_NUMBER"
          echo "NPM_VERSION_NUMBER=$NPM_VERSION_NUMBER" >> $GITHUB_ENV

      - name: Update GitHub PR comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: 'snapshot_version_comment'
          message: |
            Snapshot version published

            ```
            npm install prosekit@${{ env.NPM_VERSION_NUMBER }}
            ```
