name: Snapshot Release

on:
  issue_comment:
    types: [created]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    # check if the comments come from pull request, exclude those from issue
    if: ${{ contains(github.event.comment.html_url, '/pull/') && contains(github.event.comment.body, '/publish') }}
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup

      - name: Add changeset
        run: cp config/snapshot-changeset.md .changeset/

      - name: Update package version
        run: pnpm ci:version:next

      - name: Publish to NPM
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ".npmrc"
          pnpm ci:publish:next
          rm ".npmrc"
